name: hello world

on:
  workflow_dispatch:  # This allows manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Print success
        run: |
          echo "This job now succeeds!"
          exit 0

