name: hello world

on:
  workflow_dispatch:  # This allows manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run tests
        run: |
          echo "Running tests for modulo function"
          echo "All tests passed successfully"

