name: hello world

on:
  workflow_dispatch:  # This allows manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Print exit
        run: |
          exit 1 

# Triggering a fresh run of all check suites to resolve the queued codegen-sh-staging check
